site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Practica 1: practica1.md
    - Practica 2: practica4.5.md

theme:
    name: material
    font: 
        text: Roboto Mono
    language: es
    icon:
        logo: material/library-outline
    features:
        - header.autohide